services:
  test_postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: test_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5436:5432"