[project]
name = "brats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.18.4",
    "auth0-fastapi-api>=1.0.0b5",
    "bentoml>=1.4.36",
    "fastapi>=0.115.14",
    "httpx>=0.28.1",
    "mlflow==3.10.0",
    "monai>=1.5.2",
    "psycopg2-binary>=2.9.11",
    "pydantic[email]>=2.12.5",
    "pydantic-settings>=2.13.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.22",
    "sqlalchemy>=2.0.48",
    "uvicorn>=0.34.3",
    "google-cloud-storage>=3.9.0",
    "nibabel==5.3.3",
    "tqdm>=4.67.3",
    "openai>=2.29.0",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "prometheus-client>=0.24.1",
    "redis>=7.4.0",
    "torch>=2.11.0",
]
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }
torchaudio = { index = "pytorch-cpu" }


[dependency-groups]
dev = [
    "ruff>=0.15.5",
]

# ======================
# RUFF CONFIG
# ======================

[tool.ruff]
line-length = 88
target-version = "py310"
fix = true   # ✅ هنا مكانه الصحيح

[tool.ruff.lint]
select = [
    "E",   # errors
    "F",   # pyflakes
    "I",   # import sorting
    "B",   # bugbear
    "C4",  # comprehensions
    "UP",  # python upgrade
]
ignore = [
    "E501"
]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
