"""change name to nullable

Revision ID: 2274aa092059
Revises: 544f09293a9a
Create Date: 2026-03-15 00:34:33.620385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2274aa092059'
down_revision: Union[str, Sequence[str], None] = '544f09293a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_auth0_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.create_unique_constraint(op.f('users_auth0_id_key'), 'users', ['auth0_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
