"""make email in users table nullable

Revision ID: 322281f09ea7
Revises: 2274aa092059
Create Date: 2026-03-16 21:22:36.448696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "322281f09ea7"
down_revision: str | Sequence[str] | None = "2274aa092059"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
