# =========================
# 🧱 Stage 1: Builder
# =========================
FROM python:3.10-slim-bookworm AS builder

RUN apt-get update && apt-get upgrade -y

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1

# تثبيت uv
RUN pip install --no-cache-dir uv

# نسخ dependencies
COPY pyproject.toml uv.lock* ./



# تثبيت dependencies بدون torch أولاً
RUN uv sync --frozen --no-cache && \
    rm -rf /root/.cache

# =========================
# 🚀 Stage 2: Runtime
# =========================
FROM python:3.10-slim

WORKDIR /app

# نسخ البيئة
COPY --from=builder /app/.venv /app/.venv


# نسخ الكود
COPY ./app /app/app

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]