# =========================
# 🧱 Stage 1: Builder
# =========================
FROM python:3.10-slim AS builder

RUN apt-get update && apt-get upgrade -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock* ./

RUN uv sync --frozen --no-cache && \
    rm -rf /root/.cache

# =========================
# 🚀 Stage 2: Runtime
# =========================
FROM python:3.10-slim

RUN apt-get update && apt-get upgrade -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1

COPY --from=builder /app/.venv /app/.venv

COPY ./services/bento /app
COPY ./app /app/app

# import الموديل داخل الصورة
COPY ./services/bento/brats_model.bentomodel /tmp/brats_model.bentomodel
RUN /app/.venv/bin/bentoml models import /tmp/brats_model.bentomodel && \
    rm /tmp/brats_model.bentomodel

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app

EXPOSE 3000

CMD ["bentoml", "serve", "service:BratsService", "--port", "3000"]